### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by konsumer** [konsumer/beatstep#6]
Getting lots of requests for windows support in comments [on the video](https://youtu.be/WsXOr8mA1gY).

Node program should work fine on windows, but needs testing, and it might be helpful to setup CI to build it as a standalone package for them.

This is a bit complicated because MIDI uses native modules, and those generally have issues being pre-compiled for windows on other platforms, but maybe I can build it in CI.

**Comment by konsumer** [comment]
`pkg` currently seems broken. Latest [release on pkg-fetch](https://github.com/vercel/pkg-fetch/releases) is 18.5.0.

```
> nvm use 18.5.0
> node --version
v18.5.0

> npm run build:cli

Error! No available node version satisfies 'node18'
```

**Comment by konsumer** [comment]
Upgrading to `pkg@5.8.0` seems to have fixed pkg, but then it can't build native module:

```
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm ERR! code 1
npm ERR! path /Users/konsumer/Desktop/otherdev/beatstep/node_modules/midi
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.5.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.10.8 found at "/usr/local/opt/python@3.10/bin/python3.10"
npm ERR! gyp http GET https://nodejs.org/download/release/v18.5.0/node-v18.5.0-headers.tar.gz
npm ERR! gyp http 522 https://nodejs.org/download/release/v18.5.0/node-v18.5.0-headers.tar.gz
npm ERR! gyp WARN install got an error, rolling back install
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: 522 response downloading https://nodejs.org/download/release/v18.5.0/node-v18.5.0-headers.tar.gz
npm ERR! gyp ERR! stack     at go (/Users/konsumer/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:153:17)
npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
npm ERR! gyp ERR! stack     at async install (/Users/konsumer/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:62:18)
npm ERR! gyp ERR! System Darwin 22.1.0
npm ERR! gyp ERR! command "/Users/konsumer/.nvm/versions/node/v18.5.0/bin/node" "/Users/konsumer/.nvm/versions/node/v18.5.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/konsumer/Desktop/otherdev/beatstep/node_modules/midi
npm ERR! gyp ERR! node -v v18.5.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/konsumer/.npm/_logs/2022-12-04T20_53_56_250Z-debug-0.log
```

Upgrading to latest stable node (19) fixes `npm i` but then pkg can't deal:

```
 Error! No available node version satisfies 'node19'
```
